FROM python:3.9.12

COPY ./entregable_Lisa.py /app/
COPY ./requirements.txt /app/

WORKDIR /app/
RUN mkdir General
RUN mkdir Personajes

RUN pip install -r requirements.txt

CMD ["python3","entregable_Lisa.py"]
