# -*- coding: utf-8 -*-
"""Entregable 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eFy-N5wJTOZy5an-zcx_2sOAkFC3X7-J
"""

import requests
import json
import time
import pandas as pd

general = {}
homer = {}
lisa = {}

while True:
  URL = 'https://thesimpsonsquoteapi.glitch.me/quotes'
  respuesta = requests.get(url = URL)
  datos = respuesta.json()
  
  frase: str = datos[0]["quote"]
  personaje: str = datos[0]["character"]
  imagen: str = datos [0]["image"]

  if personaje == "Lisa Simpson":
    general[personaje] = frase
    general[personaje] = imagen
    lisa[personaje] = frase
    lisa[personaje] = imagen

  elif personaje == "Homer Simpson":
    general[personaje] = frase
    general[personaje] = imagen
    homer[personaje] = frase
    homer[personaje] = imagen
  else:
    general[personaje] = frase
    general[personaje] = imagen


  #print(general)

  df_gen = pd.DataFrame([key for key in general.keys()], columns=['Name'])
  df_gen['quote']= [value['quote'] for value in general.values()]
  df_gen['image']= [value['image'] for value in general.values()]
  df_homer = pd.DataFrame([key for key in homer.keys()], columns=['Name'])
  df_homer['quote']= [value['quote'] for value in homer.values()]
  df_homer['image']= [value['image'] for value in homer.values()]
  df_lisa = pd.DataFrame([key for key in lisa.keys()], columns=['Name'])
  df_lisa['quote']= [value['quote'] for value in lisa.values()]
  df_lisa['image']= [value['image'] for value in lisa.values()]


  df_gen.to_csv('general1.csv', mode= 'a', index = False, header = False)
  df_homer.to_csv('homer1.csv', mode= 'a',index = False, header = False)
  df_lisa.to_csv('lisa1.csv', mode = 'a', index = False, header = False)
  time.sleep(1)
  