version: '3'
services:
    datascience-notebook:
        image: jupyter/base-notebook:latest
        volumes:
            - /tmp/jupyter_test_dir:/home/docker_worker/work
        ports:
            - "8080:8888"
        command: "start-notebook.sh"
        user: root
        environment:
          JUPYTER_TOKEN: hi
          NB_USER: docker_worker
          NB_UID: 1008
          NB_GID: 1011
          CHOWN_HOME: 'yes'
          CHOWN_HOME_OPTS: -R