# -*- coding: utf-8 -*-
"""Entregable 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eFy-N5wJTOZy5an-zcx_2sOAkFC3X7-J
"""

import requests
import json
import time
import pandas as pd

general = {}
homer = {}
lisa = {}

while True:
  URL = 'https://thesimpsonsquoteapi.glitch.me/quotes'
  respuesta = requests.get(url = URL)
  datos = respuesta.json()
  
  frase: str = datos[0]["quote"]
  personaje: str = datos[0]["character"]

  if personaje == "Lisa Simpson":
    general[personaje] = frase
    lisa[personaje] = frase

  elif personaje == "Homer Simpson":
    general[personaje] = frase
    homer[personaje] = frase
  else:
    general[personaje] = frase

  #print(general)

  df_gen = pd.DataFrame([[key, general[key]] for key in general.keys()],
  columns=['Name', 'Quote'])
  df_homer  = pd.DataFrame([[key, homer[key]] for key in homer.keys()],
  columns=['Name', 'Quote'])
  df_lisa = pd.DataFrame([[key, lisa[key]] for key in lisa.keys()],
  columns=['Name', 'Quote'])


  df_gen.to_csv('general.csv', mode= 'a', index = False, header = False)
  df_homer.to_csv('homer.csv', mode= 'a',index = False, header = False)
  df_lisa.to_csv('lisa.csv', mode = 'a', index = False, header = False)
  time.sleep(30)
  